### ISSUE TITLE
License and other questions

### ISSUE THREAD

**Issue by jeremyworger** [hahnkoo/pattern_playback#1]
Hi there, this looks awesome!
-I'm wondering if there will be a license added for your project? 

-I also don't seem to see an upload function over @ https://splab.net/apd/d800/  
Maybe it hasn't been implemented just yet? (I am a little early) 
-Will the web verison be available here as code too? 

-Will there be a function for creating a spectrogram from a sound file, so that I can print it off, then load it back in to sonify the image?

**Comment by hahnkoo** [comment]
Hi. Thanks for your interest.

(1) Regarding license:
- Added LICENSE.md.

(2) Regarding the upload function over @ https://splab.net/apd/d800/ and the web version:
- The website you're referring to is someone else's. I'm not affiliated with them in any way. 

(3) Regarding a function for creating a spectrogram from a sound file:
- I'm not sure if I'd add such a function. It can be done rather easily with existing libraries like scipy, matplotlib, or librosa.
